from __future__ import annotations
from typing import Any, Optional, Protocol
from scraper_framework.core.models import Page, RequestSpec
from scraper_framework.parse.cards import Card


class SiteAdapter(Protocol):
    """Protocol for site-specific scraping adapters."""

    def key(self) -> str: ...
    def mode(self) -> str:  # "STATIC_HTML" | "JSON_API"
        ...

    def card_locator(self) -> str: ...
    def field_locator(self, field: str) -> Optional[str]: ...

    def extract_source_url(self, card: Card, page: Page) -> Optional[str]: ...
    def extract_field(self, card: Card, field: str, page: Page) -> Any: ...

    def next_request(self, page: Page, current: RequestSpec) -> Optional[RequestSpec]: ...